import dom from '../utils/_dom';
import searchOffers from '../utils/search';
import createContent from './_content';

let filterBar = function () {

    // RETRIEVE HEADER ELEMENT //
    let header = document.querySelector('.header');

    // GENERATE EMPTY FILTER BAR //
    let content = () => {

        // CREATE PARENT FILTER BAR ELEMENT(DIV) AND ITS ONLY CHILD ELEMENT(DIV) WITH CLASSNAMES //
        let filterbar = dom.createElementWithClassName('div', 'filterbar'),
            filterbarContent = dom.createElementWithClassName('div', 'filterbar--content filterbar--min-height filterbar--align-items');

        filterbarContent.innerHTML = "";

        // INSERT FILTER BAR AND ITS ONLY CHILD INTO HEADER //
        dom.append(header, filterbar);
        dom.append(filterbar, filterbarContent);
    };

    // GENERATE SEARCH BAR //
    let searchbar = () => {

        // CREATE SEARCH BAR ELEMENT(INPUT) WITH CLASSNAME //
        let filterbarSearch = dom.createElementWithClassName('input', 'filterbar__searchbar');

        // CHECK PREVIOUSLY CREATED SEARCH BAR ELEMENT //
        let duplicate = dom.getElement(filterbarSearch.className);
        if (duplicate !== null) {
            dom.removeElement(duplicate);
        }

        // SET ATTRIBUTES FOR SEARCH BAR //
        let filterSearchAttributes = {
            'type': 'text',
            'name': 'search',
            'placeholder': 'Search For Coupons: Yoplait, Ziploc, Downy, Detergent...'
        };
        dom.setAttributes(filterbarSearch, filterSearchAttributes);

        // INSERT SEARCH BAR INTO FILTER BAR //        
        let filterbarContent = dom.getElement('filterbar--content');
        dom.append(filterbarContent, filterbarSearch);

        // CREATE SEARCH RESULT UL //
        let filterbarSearchResults = dom.createElementWithClassName('ul', 'filterbar__searchbar__result');

        // INSERT SEARCH RESULT INTO FILTERBAR--CONTENT //
        dom.append(filterbarContent, filterbarSearchResults);

        let searchbar = dom.getElement('filterbar__searchbar');

        searchOffers(searchbar);

        searchbar.addEventListener('focus', function () {
            this.removeAttribute('placeholder');
            this.style.backgroundImage = "url('./images/searchiconhover.png')";
        });

        searchbar.addEventListener('blur', function () {
            this.setAttribute('placeholder', 'Search For Coupons: Yoplait, Ziploc, Downy, Detergent...');
            this.style.backgroundImage = "url('./images/searchicon.png')";
        });
    };

    // FUNCTION TO GENERATE SELECT DROPDOWN //
    let select = (type) => {

        // CREATE SELECT DROPDOWN ELEMENT(SELECT) WITH CLASSNAME //
        let filterbarSelect = dom.createElementWithClassName('select', 'filterbar__select'),
            filterbarSelectTitle = dom.createElementWithClassName('span', 'filterbar__select--title');

        filterbarSelectTitle.textContent = "Categories:";


        // SET ATTRIBUTES FOR SELECT DROPDOWN //
        let filterSelectAttributes = {
            'name': 'categories',
        };
        dom.setAttributes(filterbarSelect, filterSelectAttributes);

        // SEND REQUEST FOR OFFER DETAILS VIA TYPE ID//
        let url = `https://couponmatix.firebaseio.com/v0/items/${type}.json`;
        dom.getOffers(url)
            .then((result) => {

                // PARSE JSON INTO JS OBJECT //
                let offerDetails = JSON.parse(result);

                // COUNT CATEGORIES AND SAVE THEM IN CATEGORY OBJECT //
                let category = {};
                category['Show All'] = offerDetails.length;
                offerDetails.forEach((currentEl) => {
                    category[currentEl.category] = (category[currentEl.category] || 0) + 1;
                });

                // INSERT CATEGORIES INTO SELECT DROPDOWN //
                for (let cat in category) {
                    let option = dom.createElement('option');
                    if (cat == 'Show All') {
                        option.value = 'showAll';
                    } else option.value = cat;
                    option.textContent = `${cat} (${category[cat]})`;
                    filterbarSelect.appendChild(option);
                }

            })


        // INSERT SELECT DROPDOWN INTO FILTER-FRAME-RIGHT (GENERATED BY CONTENT.JS) //
        let filterFrameRight = dom.getElement('content__galery__info__filter-right');
        dom.append(filterFrameRight, filterbarSelectTitle, filterbarSelect);


        // FILTERING VIA SELECT BAR ONCHANGE //
        filterbarSelect.addEventListener('change', (e) => {
            createContent.createContentViaFiltering(type, e.target.value);
        })
    };

    let sort = () => {

        // CREATE SELECT DROPDOWN ELEMENT(SELECT) WITH CLASSNAME //
        let filterbarSort = dom.createElementWithClassName('select', 'filterbar__sort'),
            filterbarSortTitle = dom.createElementWithClassName('span', 'filterbar__sort--title');

        filterbarSortTitle.textContent = "Sort by:";

        let sortOptions = [
            'Newest',
            'Oldest',
            'Brand A-Z',
            'Brand Z-A'
        ];

        for (let opt of sortOptions) {
            let option = dom.createElement('option');
            option.textContent = option.value = opt;
            dom.append(filterbarSort, option);
        }

        // INSERT SELECT DROPDOWN INTO FILTER-FRAME-LEFT (GENERATED BY CONTENT.JS) //
        let filterFrameLeft = dom.getElement('content__galery__info__filter-left');
        dom.append(filterFrameLeft, filterbarSortTitle, filterbarSort);

        // SORTING VIA SELECT BAR ONCHANGE //
        filterbarSort.addEventListener('change', (e) => {
            createContent.createContentViaSorting(e.target.value);
        })

    }

    return {
        content: content,
        select: select,
        sort: sort,
        searchbar: searchbar
    }
}();

export default filterBar;